### ISSUE TITLE
date-selector refresh happening too early

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#605]
It appears that in the date_range.js file around line 25 we had a refresh() that is firing too soon.

//RTP I think this causes it to refresh too quickly. If we need this we should find a better way.
    //refresh();   // initial value based on what is in the superior

We need to debug this better and fix it in a better way.

**Comment by mollybsmith-noaa** [comment]
We didn't need that code, so there's no need to rewrite anything and I'm closing this issue.

**Comment by bonnystrong** [comment]
If we don't need that code, why is it there?

**Comment by mollybsmith-noaa** [comment]
It isn’t, we removed it last spring. The issue was apparently left open in
case it turned out that we *did* need it, in which case we would have to
come up with something smarter to put back in. Fortunately that was not the
case, which I am confirming by closing this issue. It should have been
closed after that release, but evidently no one remembered to do so.
