### ISSUE TITLE
create the FlowRouter route for rendering an application from a "saved settings".

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/MATS#880]
Refer to issue #878. That application link (think FlowRouter route) will need to change to be something like .... 
e.view.window.open("https://www.esrl.noaa.gov/gsd/mats/" + application + "/" + region + "/" + variable + "/" + statistic + "/" + fcst_len, "_blank"); .... and then this link must be represented by a new Flowrouter route in MATScommon/meteor_packages/mats-common/imports/startup/client/routes.js. Some of this work is to be completed under issue #879 and #880. This is the issue where the FlowRouter route is implemented that brings up an application, then programmatically restores the settings (modifying the settings with the parameters), and programmatically clicks the plot matched button.

**Comment by mollybsmith-noaa** [comment]
Placing this here for reference: https://github.com/NOAA-GSL/MATS/discussions/892

**Comment by gopa-noaa** [comment]
Instead of:
window.open("https://www.esrl.noaa.gov/gsd/mats/" + application + "/" + region + "/" + variable + "/" + statistic + "/" + fcst_len, "_blank"); 

We could make it more generic, so that it is extensible in future:
window.open("https://www.esrl.noaa.gov/gsd/mats/" + application + "/?URL encoded JSON string"); 

The JSON for now could be as simple as { "startup": "LoadSettings", "Settings": {settings JSON or db Key to JSON Object} }

Apps on load will check if the URL param JSON is present, and will act on it.
Let me know what you all think...

**Comment by mollybsmith-noaa** [comment]
Reassigning this to myself, because I'm almost done with this work.

**Comment by mollybsmith-noaa** [comment]
To continue the discussion from before, the URL will be in the form `baseURL + "/" + appSource + "/scorecardTimeseries/" + key`, with `key` being a hash that serves as the document ID in couchbase.

**Comment by mollybsmith-noaa** [comment]
This work is done.
